### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by xalgord** [PentestPad/subzy#39]
why I'm getting this error:

![image](https://github.com/LukaSikic/subzy/assets/48483027/06d996ac-8110-442f-b96a-e440f0894968)

**Comment by matthewomccorkle** [comment]
@xalgord you are receiving this error because you are using a shell script file as your input. Try running Subzy with a correctly formatted targets file. See the list.txt example file located in the repository for how to format a list of subdomains as a target file. https://github.com/PentestPad/subzy/blob/master/list.txt

**Comment by LukaSikic** [comment]
Thanks @matthewomccorkle !
